### PR TITLE
added new file

### PR DESCRIPTION
**Pull request by RonakR**
Check out the file I added

### CODE REVIEW

**Comment by FitzChivalry** [comment]
Didn't delete the previous class before starting the next?  ;-)

**Comment by RonakR** [comment]
Branches are still there but master is clean

**Comment by FitzChivalry** [comment]
Check out the repository I created for my project after your class: https://github.com/CarolinaKinetic/Cat5Scouting :-)

I'll be sending my wife to your class, soon.

**Comment by RonakR** [comment]
Pretty awesome dude! Looking forward to helping her with Git too.

**Pull request merged**
