### PR TITLE
Memes go here

### PR DESCRIPTION
**Pull request by RonakR**

### CODE REVIEW

**Comment by adamcollias** [comment]
Please remove me from this thread.

**Comment by kirby2701** [comment]
Please remove me from this thread also.

**Comment by levimogg** [comment]
Hi there!  

Really enjoyed the class when I took it. Please take me off the thread. :D

Thanks!

 
Best,
Levi Mogg

Email: Levimogg@gmail.com
Phone: (252) 676-0060
Twitter: @levimogg

**Comment by RonakR** [comment]
You guys need to this yourself. Go to `Settings`, there should be a tab for `Collaborations and Team` or something along those lines, I don't the exact button combo because I can't see that view. But the option should be there.

**Comment by FitzChivalry** [comment]
Not sure if this email will go to the right people, but:
1. If you aren't logged in with your Github account, log in2. Navigate to https://github.com/chscodecamp/github/3. Click the icon in the upper right corner of the screen.4. Click the Settings menu.5. On the page that loads, click the Organizations menu link on the left.6. Click the Leave button to the right of "chscodecamp." David Castro
github-email@spamex.com
843.595.4571 
 

    On Wednesday, May 11, 2016 9:19 PM, Ronak Raithatha <notifications@github.com> wrote:
 

 You guys need to this yourself. Go to Settings, there should be a tab for Collaborations and Team or something along those lines, I don't the exact button combo because I can't see that view. But the option should be there. —

**Comment by RonakR** [comment]
Give this man a medal!

**Comment by kirby2701** [comment]
I want to be taken off the thread.

**Comment by britchar** [comment]
Take me off too please!

Britney Charles
Release Coordinator
Benefitfocus - Benefits are good.(tm)
p. 843-284-1052 ext. 6979<tel:843-284-1052;6979>
c. 843-901-2336<tel:843-901-2336>
f. 843-849-9485<tel:843-849-9485>


On May 11, 2016, at 9:28 PM, kirby2701 <notifications@github.com<mailto:notifications@github.com>> wrote:

I want to be taken off the thread.
On May 11, 2016 9:27 PM, "Ronak Raithatha" <notifications@github.com<mailto:notifications@github.com>> wrote:

> Give this man a medal!
>
> -
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/chscodecamp/github/pull/5#issuecomment-218636146>
>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/chscodecamp/github/pull/5#issuecomment-218636260>

Benefitfocus (NASDAQ: BNFT) provides a leading cloud-based benefits management platform that simplifies how organizations and individuals shop for, enroll in, manage and exchange benefits. Every day leading employers, insurance companies and millions of consumers rely on our platform to manage, scale and exchange benefits data seamlessly. In an increasingly complex benefits landscape, we bring order to chaos so our clients and their employees have access to better information, make better decisions and lead better lives. Learn more at www.benefitfocus.com<http://www.benefitfocus.com>, LinkedIn<https://www.linkedin.com/company/benefitfocus> and Twitter<http://www.twitter.com/benefitfocus>.

**Comment by mimoore** [comment]
Mmmmmm me lurvs memes

**Comment by MajorDean009** [comment]
Please remove from this email list.

Quoting mimoore <notifications@github.com>:

> Mmmmmm me lurvs memes
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/chscodecamp/github/pull/5#issuecomment-218638429



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by MajorDean009** [comment]
DO NOT SPAM ME AGAIN :(

Please remove from this list.

This email does not have an unsubscribe link!



Quoting Ronak Raithatha <notifications@github.com>:

>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/chscodecamp/github/pull/5
>
> -- Commit Summary --
>
>   * Up to no good
>   * Merge branch 'master' into memesGoHere
>
> -- File Changes --
>
>     A meme.txt (1)
>
> -- Patch Links --
>
> https://github.com/chscodecamp/github/pull/5.patch
> https://github.com/chscodecamp/github/pull/5.diff
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/chscodecamp/github/pull/5
>



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by jetgo1000** [comment]
People, you have to go to your account and change your settings. No one can
remove you from "the list" but yourself.

**Comment by erikadgreco** [comment]
STEP 1:

STEP 2:
​
​

STEP 3:
​

On Thu, May 12, 2016 at 1:18 PM, jetgo1000 <notifications@github.com> wrote:

> People, you have to go to your account and change your settings. No one can
> remove you from "the list" but yourself.
>
> On Thu, May 12, 2016 at 1:15 PM MajorDean009 <notifications@github.com>
> wrote:
>
> > DO NOT SPAM ME AGAIN :(
> >
> > Please remove from this list.
> >
> > This email does not have an unsubscribe link!
> >
> >
> >
> > Quoting Ronak Raithatha <notifications@github.com>:
> >
> > >
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/chscodecamp/github/pull/5
> > >
> > > -- Commit Summary --
> > >
> > > * Up to no good
> > > * Merge branch 'master' into memesGoHere
> > >
> > > -- File Changes --
> > >
> > > A meme.txt (1)
> > >
> > > -- Patch Links --
> > >
> > > https://github.com/chscodecamp/github/pull/5.patch
> > > https://github.com/chscodecamp/github/pull/5.diff
> > >
> > > ---
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/chscodecamp/github/pull/5
> > >
> >
> >
> >
> > ----------------------------------------------------------------
> > This message was sent using IMP, the Internet Messaging Program.
> >
> > —
> >
> >
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/chscodecamp/github/pull/5#issuecomment-218824147>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chscodecamp/github/pull/5#issuecomment-218824970>
>



-- 

*Erika Greco*Implementation Specialist
843.518.6059 :: BoomTownROI.com <http://www.boomtownroi.com/>
<http://boomtownroi.com/>[image: www.boomtownroi.com/referral]
<http://go.boomtownroi.com/referral?utm_campaign=Referral_Program&utm_content=Success_Manager&utm_medium=Email&utm_source=Email>

**Comment by karanbajwa** [comment]
go to settings, organizations and LEAVE the group.

On 12 May 2016 at 13:15, MajorDean009 <notifications@github.com> wrote:

> DO NOT SPAM ME AGAIN :(
>
> Please remove from this list.
>
> This email does not have an unsubscribe link!
>
>
>
> Quoting Ronak Raithatha <notifications@github.com>:
>
> >
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/chscodecamp/github/pull/5
> >
> > -- Commit Summary --
> >
> > * Up to no good
> > * Merge branch 'master' into memesGoHere
> >
> > -- File Changes --
> >
> > A meme.txt (1)
> >
> > -- Patch Links --
> >
> > https://github.com/chscodecamp/github/pull/5.patch
> > https://github.com/chscodecamp/github/pull/5.diff
> >
> > ---
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/chscodecamp/github/pull/5
> >
>
>
>
> ----------------------------------------------------------------
> This message was sent using IMP, the Internet Messaging Program.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chscodecamp/github/pull/5#issuecomment-218824147>
>



-- 
Cheers!
Karan

**Comment by vVfishVv** [comment]
You have to remove yourself in github

**Comment by RonakR** [comment]
Hey everyone, 
If you want to get removed from this you're going to have to do it yourself, mostly because I do not want each and one of the students that went to this class to be sending me emails to get removed from this thread or the whole org. 

So, what I'm going to ask you all to do is to go the link provided in your that takes you to GitHub, now I know this may hard for some folks so I'll paste the link here just in case, https://github.com/chscodecamp/github/pull/5.
 
Now, when you get to that page you've got a whole new world of options here. 
1) You can choose to `Unsubscribe` from this thread by hitting the button that says `Unsubscribe` on the right-hand side. 
2) You can choose to `Unwatch` this repository and not get notified about anything going on there by clicking the `Unwatch` button on the top right side of the page, under the nav bar. 
3) You can choose not be a part of this repository anymore by going to `Settings` on this page, and then to `Organizations` and clicking the leave button. 

I hope this helps. Feel free to ask me any more questions here, I encourage it so we can keep spamming each other.

**Comment by bodhisattva082915** [comment]
Lolz, there is so much fail in this thread.
>2016
>how do I keep track of my own github?
>how do I hold all this spaghetti?

**Comment by aeChurch** [comment]
[image: Inline image 3]

On Thu, May 12, 2016 at 2:56 PM, Andrew Bettke <notifications@github.com>
wrote:

> Lolz, there is so much fail in this thread.
> >2016
> >how do I keep track of my own github?
> >how do I hold all this spaghetti?
> On May 12, 2016 1:33 PM, "Ronak Raithatha" <notifications@github.com>
> wrote:
>
> > Hey everyone,
> > If you want to get removed from this you're going to have to do it
> > yourself, mostly because I do not want each and one of the students that
> > went to this class to be sending me emails to get removed from this
> thread
> > or the whole org.
> >
> > So, what I'm going to ask you all to do is to go the link provided in
> your
> > that takes you to GitHub, now I know this may hard for some folks so I'll
> > paste the link here just in case, #5
> > <https://github.com/chscodecamp/github/pull/5>.
> >
> > Now, when you get to that page you've got a whole new world of options
> > here.
> > 1) You can choose to Unsubscribe from this thread by hitting the button
> > that says Unsubscribe on the right-hand side.
> > 2) You can choose to Unwatch this repository and not get notified about
> > anything going on there by clicking the Unwatch button on the top right
> > side of the page, under the nav bar.
> > 3) You can choose not be a part of this repository anymore by going to
> > Settings on this page, and then to Organizations and clicking the leave
> > button.
> >
> > I hope this helps. Feel free to ask me any more questions here, I
> > encourage it so we can keep spamming each other.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/chscodecamp/github/pull/5#issuecomment-218829138>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/chscodecamp/github/pull/5#issuecomment-218852496>
>

ᐧ

**Comment by MajorDean009** [comment]
STOP SPAMMING with these Messages  :(

I NEVER Subscribed to this list and there is no un-sub link on this  
email either :(


Quoting aeChurch <notifications@github.com>:

> [image: Inline image 3]
>
> On Thu, May 12, 2016 at 2:56 PM, Andrew Bettke <notifications@github.com>
> wrote:
>
>> Lolz, there is so much fail in this thread.
>> >2016
>> >how do I keep track of my own github?
>> >how do I hold all this spaghetti?
>> On May 12, 2016 1:33 PM, "Ronak Raithatha" <notifications@github.com>
>> wrote:
>>
>> > Hey everyone,
>> > If you want to get removed from this you're going to have to do it
>> > yourself, mostly because I do not want each and one of the students that
>> > went to this class to be sending me emails to get removed from this
>> thread
>> > or the whole org.
>> >
>> > So, what I'm going to ask you all to do is to go the link provided in
>> your
>> > that takes you to GitHub, now I know this may hard for some folks so I'll
>> > paste the link here just in case, #5
>> > <https://github.com/chscodecamp/github/pull/5>.
>> >
>> > Now, when you get to that page you've got a whole new world of options
>> > here.
>> > 1) You can choose to Unsubscribe from this thread by hitting the button
>> > that says Unsubscribe on the right-hand side.
>> > 2) You can choose to Unwatch this repository and not get notified about
>> > anything going on there by clicking the Unwatch button on the top right
>> > side of the page, under the nav bar.
>> > 3) You can choose not be a part of this repository anymore by going to
>> > Settings on this page, and then to Organizations and clicking the leave
>> > button.
>> >
>> > I hope this helps. Feel free to ask me any more questions here, I
>> > encourage it so we can keep spamming each other.
>> >
>> > ?
>> > You are receiving this because you are subscribed to this thread.
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/chscodecamp/github/pull/5#issuecomment-218829138>
>>
>> >
>>
>> ?
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chscodecamp/github/pull/5#issuecomment-218852496>
>>
>
> ?
>
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chscodecamp/github/pull/5#issuecomment-218853648



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by MajorDean009** [comment]
STOP SPAMMING with these Messages  :(

I NEVER Subscribed to this list and there is no un-sub link on this  
email either :(




Quoting Andrew Bettke <notifications@github.com>:

> Lolz, there is so much fail in this thread.
>> 2016
>> how do I keep track of my own github?
>> how do I hold all this spaghetti?
> On May 12, 2016 1:33 PM, "Ronak Raithatha" <notifications@github.com> wrote:
>
>> Hey everyone,
>> If you want to get removed from this you're going to have to do it
>> yourself, mostly because I do not want each and one of the students that
>> went to this class to be sending me emails to get removed from this thread
>> or the whole org.
>>
>> So, what I'm going to ask you all to do is to go the link provided in your
>> that takes you to GitHub, now I know this may hard for some folks so I'll
>> paste the link here just in case, #5
>> <https://github.com/chscodecamp/github/pull/5>.
>>
>> Now, when you get to that page you've got a whole new world of options
>> here.
>> 1) You can choose to Unsubscribe from this thread by hitting the button
>> that says Unsubscribe on the right-hand side.
>> 2) You can choose to Unwatch this repository and not get notified about
>> anything going on there by clicking the Unwatch button on the top right
>> side of the page, under the nav bar.
>> 3) You can choose not be a part of this repository anymore by going to
>> Settings on this page, and then to Organizations and clicking the leave
>> button.
>>
>> I hope this helps. Feel free to ask me any more questions here, I
>> encourage it so we can keep spamming each other.
>>
>> ?
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/chscodecamp/github/pull/5#issuecomment-218829138>
>>
>
>
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chscodecamp/github/pull/5#issuecomment-218852496



----------------------------------------------------------------
This message was sent using IMP, the Internet Messaging Program.

**Comment by dash-comment** [comment]
A new meme is born!? Please keep the unsubscribe requests coming and never RTFM.

Thanks all for the foo!

Sarcastically yours,

C.

**Comment by vVfishVv** [comment]
To remove yourself from comments within GitHub you need to unwatch the
repositories. There are other ways to do this, such as turning off email
notifications, however it would prevent you from seeing notifications you
wish to see. Simply be logged into GitHub and follow this link Unwatch
Specific Repositories <https://github.com/watching>
You're welcome :)
VfishV

**Comment by WSCody** [comment]
Me too

W.S. Cody Burg
Hello Home Inspection Services
www.hellohomeservices.com
Lic. RBI 48770
(843) 345 9325

**Comment by adamz00** [comment]
unsub me, a haiku

dear god someone plz
find the unsubscribe button
and click it for me

**Comment by RonakR** [comment]
HEY EVERYONE, this is your instructor. READ THIS.

You have all been taken off the GitHub repository since yesterday, but when
someone still keeps replying to this it SEEMS like you are all still in the
thread.
You're not, now stop replying here.

Thanks,
Ron

**Comment by adamz00** [comment]
what if we want to
because it is so much fun
to keep trolling your inbox

**Comment by adamz00** [comment]
aw shit counting fail, fine you win

**Comment by vVfishVv** [comment]
Well. They might still be subscribed to the thread.

**Comment by dash-comment** [comment]
Okay guys, version-control yourselves!

**Comment by dash-comment** [comment]
Okay guys, version-control yourselves!

**Pull request merged**
